# Generated by Django 3.0.5 on 2023-11-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_employees_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='image',
        ),
    ]
