# Generated by Django 3.0.5 on 2023-11-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_employees_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
